config/routes.rb
Livreiro::Application.routes.draw do
  get "users/books"

  get "users/lended"

  get "users/lent"

  resources :books do
    collection do
      get 'free'
      get 'search'
    end
    member do
      post 'lend'
      post 'return'
    end
  end
  
  resources :users, :only => [] do 
    member do
      get 'books'
      get 'lended'
      get 'lent'
    end
  end
  
  get "home/index"
  devise_for :users
  root :to => "books#index"

end

app/models/book.rb
# encoding: UTF-8
class Book < ActiveRecord::Base
  scope :free, where("with_id is null")
  scope :lent, where("with_id is not null")

  Locations = ["SP", "MG"]
  Categories = ["Gestão empresarial", "Auto ajuda", "Gastronomia", "Dicionários e Gramática", "Engenharia e Tecnologia", "Empreendedorismo e inovação", "Outros"]

  searchable do
    text :title, :default_boost => 3
    text :author, :default_boost => 2
    text :owner_name do 
      owner.name
    end
    boolean :free do
      with_id == nil
    end
    text :category, :default_boost => 1
    text :isbn
    integer :with_id, :references => User
    integer :owner_id, :references => User
  end

  def lend(user)
    self.with = user
    self.save!
  end

  def return
    self.with = nil
    self.save!
  end

  belongs_to :owner, :class_name => "User"
  belongs_to :with, :class_name => "User"
  validates_presence_of :owner, :title, :author
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  validates_presence_of :email, :name

  has_many :books, :foreign_key => 'owner_id'
  has_many :loans, :foreign_key => 'with_id', :class_name => 'Book'

  def to_s
    self.name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  protected
  def deny!(message = "Acesso negado.")
    flash[:notice] = message    
    redirect_to root_path 
  end
  
  def collect_page
    @page = params[:page] || 1
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_filter :authenticate_user!
  before_filter :collect_page

  def free
    @books = Book.free.page(@page)

    respond_to do |format|
      format.html
      format.xml { render :xml => @books }
    end
  end

  # GET /books
  # GET /books.xml
  def index
    page = params[:page] || 1
    @books = Book.page(@page)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @books }
    end
  end

  # GET /books/1
  # GET /books/1.xml
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @book }
    end
  end

  # GET /books/new
  # GET /books/new.xml
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @book }
    end
  end

  def lend
    @book = Book.find(params[:id])
    @book.lend current_user
    flash[:notice] = "Voce pegou #{@book.title} emprestado de #{@book.owner}."
    redirect_to :back
  end

  def return 
    @book = Book.find(params[:id])
    @book.return
    flash[:notice] = "Voce devolveu #{@book.title} para #{@book.owner}."
    redirect_to :back
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
    deny! unless @book.owner == current_user
  end

  # POST /books
  # POST /books.xml
  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to(books_path, :notice => 'Livro criado.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.xml
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to(books_path, :notice => 'Livro atualizado.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @book.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.xml
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to(books_url) }
      format.xml  { head :ok }
    end
  end

  def search 
    word = params[:keywords] || ''
    @search = Book.search do
      fulltext(word) 
      with(:free, true) if params.has_key? :free
      paginate(:page => params[:page], :per_page => 10)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :current_user!, :only => [:lended, :lent]
  before_filter :collect_page
  
  def books
    @books = User.find(params[:id]).books.page(@page)
  end

  def lended
    @books = current_user.books.lent.page(@page)
  end

  def lent
    @books = current_user.loans.page(@page)
  end

  private 
    def current_user!
      deny! unless current_user.id.to_s == params[:id]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_menu(lbl, url, hash = {})
    if current_page? url
      le_class = 'active '
      if hash.has_key?(:class)
        le_class = le_class << hash[:class] 
      end
      hash.merge!({:class => le_class})
    end
    link_to(lbl, url, hash)
  end
end

app/helpers/books_helper.rb
module BooksHelper
  def all_books
    Book.count
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_busca.html.erb
<div id="busca">
  <%= form_tag search_books_path, :method => "get" do %>
    <%= label_tag :keywords, "Buscar" %>
    <%= text_field_tag :keywords %>
	<%= label_tag :free, "Livre" %>
	<%= check_box_tag :free %>
    <%= submit_tag "Enviar" %>
  <% end %>
</div>

app/views/books/_form.html.erb
<%= simple_form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2>Aconteceu algum problema! Cheque esses campos:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.input :title, :label => "Título" %><br />
  </div>
  <div class="field">
    <%= f.input :author, :label => "Autor" %><br />
  </div>
  <div class="field">
    <%= f.input :isbn, :label => "ISBN" %><br />
  </div>
  <div class="field">
    <%= f.input :category, :collection => Book::Categories, :label => "Categoria" %>
    <br />
  </div>
  <div class="field">
    <%= f.input :current_location, :collection => Book::Locations, :label => "Localização" %>
    <br />
  </div>
  <div class="field">
    <%= f.input :pages, :label => "Páginas" %><br />
  </div>
  <%= f.hidden_field :owner_id, :value => current_user.id %>
  <div class="actions">
    <%= f.submit "Cadastrar" %>
  </div>
<% end %>

app/views/books/_list.html.erb
<table id="listing">
  <tr>
    <th>Título</th>
    <th>Autor</th>
    <th>ISBN</th>
    <th>Categoria</th>
    <th>Local</th>
    <th>P&aacute;ginas</th>
    <th>Dono</th>
    <th>Locador</th>
    <th></th>
    <th></th>
  </tr>

<% @books.each do |book| %>
  <tr>
    <td><%= book.title %></td>
    <td><%= book.author %></td>
    <td><%= book.isbn %></td>
    <td><%= book.category %></td>
    <td><%= book.current_location %></td>
    <td><%= book.pages %></td>
    <td><%= book.owner %></td>
    <td><%= book.with %></td>
    <td>
      <% if book.owner == current_user %>
        <%= link_to 'Editar', edit_book_path(book) %>
      <% elsif book.with == nil %>
        <%= link_to 'Emprestar', lend_book_path(book), :method => :post %>
      <% elsif book.with == current_user %>
        <%= link_to 'Devolver', return_book_path(book), :method => :post %>
      <% end %>
    </td>
	<td>
	<% if book.owner == current_user %>
	    <%= link_to('Apagar', book, :confirm => 'Tem certeza?', :method => :delete) %>
	<% end %>
	</td>
  </tr>
<% end %>
</table>
<div id="navigation">
  <%= paginate @books %>
</div>

app/views/books/edit.html.erb
<h1>Editando Livro</h1>

<%= render 'form' %>

app/views/books/free.html.erb
<h1>Livros Dispon&iacute;veis</h1>
<%= render 'list' %>
<br />

app/views/books/index.html.erb
<%= render 'books/busca' %>
<h1>Todos os Livros</h1>
<%= render 'list' %>

app/views/books/new.html.erb
<h1>Cadastrar Livro</h1>

<%= render 'form' %>

<%= link_to 'Voltar', books_path %>

app/views/books/search.html.erb
<%= render 'books/busca' %>
<table>
  <tr>
    <th>Título</th>
    <th>Autor</th>
    <th>ISBN</th>
    <th>Categoria</th>
    <th>Local</th>
    <th>P&aacute;ginas</th>
    <th>Dono</th>
    <th>Locador</th>
    <th></th>
    <th></th>
  </tr>

<% @search.each_hit_with_result do |hit, book| %>
  <tr>
    <td><%= book.title %></td>
    <td><%= book.author %></td>
    <td><%= book.isbn %></td>
    <td><%= book.category %></td>
    <td><%= book.current_location %></td>
    <td><%= book.pages %></td>
    <td><%= book.owner %></td>
    <td><%= book.with %></td>
    <td>
      <% if book.owner == current_user %>
        <%= link_to 'Editar', edit_book_path(book) %>
      <% elsif book.with == nil %>
        <%= link_to 'Emprestar', lend_book_path(book), :method => :post %>
      <% elsif book.with == current_user %>
        <%= link_to 'Devolver', return_book_path(book), :method => :post %>
      <% end %>
    </td>
    <td><%= link_to('Apagar', book, :confirm => 'Tem certeza?', :method => :delete) if book.owner == current_user %></td>
  </tr>
<% end %>
</table>
<div id="navigation">
  <%= paginate @search %>
</div>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @book.title %>
</p>

<p>
  <b>Author:</b>
  <%= @book.author %>
</p>

<p>
  <b>Category:</b>
  <%= @book.category %>
</p>

<p>
  <b>Pages:</b>
  <%= @book.pages %>
</p>

<p>
  <b>Owner:</b>
  <%= @book.owner %>
</p>

<p>
  <b>With:</b>
  <%= @book.with %>
</p>


<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Livreiro - Arquivo e Compartilhamento de livros</title>
	<%= stylesheet_link_tag :all %>
	<%= javascript_include_tag :all %>
	<%= csrf_meta_tag %>
</head>
<body>
	<div id="header">
          <a class="logo" href="<%=root_path%>">Livreiro</a>
		<div class="menu">
			<% if user_signed_in? %>
				<div class="welcome">
					Olá <%= current_user.name %>. <%= link_to "Sair", destroy_user_session_path, :method => :delete %>
				</div>
				<div class="links">
					<%= link_to_menu "Adicionar Livro", new_book_path %>
					<%= link_to_menu "Todos os Livros", root_path %>
					<%= link_to_menu "Livros Disponíveis", free_books_path %>
					<%= link_to_menu "Seus Livros", books_user_path(current_user) %>
					<%= link_to_menu "Livros com você", lent_user_path(current_user) %>
					<%= link_to_menu "Livros Emprestados", lended_user_path(current_user) %>
				</div>
			<% end %>
		</div>
	</div>
	<div id="main-content">
  		<div class="messages">
    		<p class="notice"><%= notice %></p>
    		<p class="alert"><%= alert %></p>
  		</div>
		<%= yield %>
	</div>
</body>
</html>

app/views/users/books.html.erb
<%= render 'books/list' %>

app/views/users/lended.html.erb
<%= render 'books/list' %>

app/views/users/lent.html.erb
<%= render 'books/list' %>
<br />